server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:4000 # veya lb://patient-service
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1 # İyileştirildi

        # Gelen istek: localhost:4004/api-docs/patients
        # Hedef: patient-service:4000/v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4000 # veya lb://patient-service
          predicates:
            - Path=/api-docs/patients # DÜZELTİLDİ: Yorum ve RewritePath ile tutarlı hale getirildi
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs # İyileştirildi ve okunurluk için virgülden sonra boşluk