server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        ## predicates -> (I think gateway will undestand prom predicates which service is this) Strip path side add uri for requests http://localhost:4004/api/patients
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - path=/api/patients/**
          filters:
            - strip-prefix=1

        ## Client when send request to localhost:4004/api-docs/patients gateway will send it to patient-service:4000/v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
              - path=//api-cos/patients
          filters:
            - rewrite-path=/api-docs/patients,/v3/api-docs



