version: '3.8'
services:
  billing-service:
    container_name: billing-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - my-network


networks:
  my-network:
    external: true